import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Star, MapPin, ArrowRight, MessageCircle,
  Zap, Package, Navigation, Send, X, Loader,
  CheckCircle, AlertCircle, Truck, Tag
} from 'lucide-react'
import api from '../api/axios'

// ── Sabitler ────────────────────────────────────────────────
const LOCATION_CONFIG = {
  muhendislik:   { label: 'Mühendislik',   cls: 'bg-blue-50 text-blue-600 border-blue-200'     },
  merkez_kantin: { label: 'Merkez Kantin', cls: 'bg-orange-50 text-orange-600 border-orange-200' },
  yabanci_dil:   { label: 'Yabancı Dil',  cls: 'bg-purple-50 text-purple-600 border-purple-200' },
  sosyal_yasam:  { label: 'Sosyal Yaşam', cls: 'bg-pink-50 text-pink-600 border-pink-200'       },
  kutuphane:     { label: 'Kütüphane',    cls: 'bg-teal-50 text-teal-600 border-teal-200'       },
}

const TASK_TYPE_CONFIG = {
  skill_exchange:  { label: 'Yetenek Takası', icon: Zap,        cls: 'bg-white/10 text-slate-700 border-white/15'      },
  courier_request: { label: 'Kurye Talebi',   icon: Package,    cls: 'bg-amber-50 text-amber-700 border-amber-200'       },
  courier_offer:   { label: 'Kurye Teklifi',  icon: Navigation, cls: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  second_hand:     { label: 'İkinci El',      icon: Tag,        cls: 'bg-indigo-50 text-indigo-700 border-indigo-200'    },
}

// ── Yıldız ─────────────────────────────────────────────────
function StarRating({ value, count }) {
  const numericValue = Number(value || 0)
  return (
    <div className="flex items-center gap-1">
      <div className="flex gap-0.5">
        {[1,2,3,4,5].map((s) => (
          <Star
            key={s}
            size={11}
            className={s <= Math.round(numericValue) ? 'text-amber-400 fill-amber-400' : 'text-slate-200 fill-slate-100'}
          />
        ))}
      </div>
      <span className="text-[11px] text-slate-400">
        {numericValue.toFixed(1)} ({count || 0})
      </span>
    </div>
  )
}

// ── Görevi Kabul Onay Modalı ────────────────────────────────
function ConfirmAssignModal({ task, onConfirm, onCancel, loading }) {
  const typeConf = TASK_TYPE_CONFIG[task.task_type] || TASK_TYPE_CONFIG.skill_exchange
  const TypeIcon = typeConf.icon

  const isAutoGenerated = task.is_auto_generated
  const isCourierOffer  = task.task_type === 'courier_offer'

  const locationDisplay = task.task_type === 'courier_offer' && task.from_location && task.to_location
    ? `${LOCATION_CONFIG[task.from_location]?.label} → ${LOCATION_CONFIG[task.to_location]?.label}`
    : task.location ? LOCATION_CONFIG[task.location]?.label : null

  const paymentNote = isCourierOffer
    ? `Bu görevi kabul ederseniz ${task.effective_reward || task.reward_kredi} KP ödeyeceksiniz.`
    : isAutoGenerated
      ? `Bu görevi kabul ederseniz ${task.reward_kredi} KP anında cüzdanınıza yatırılacak. 🚚`
      : `Bu görevi tamamlayarak ${task.effective_reward || task.reward_kredi} KP kazanacaksınız.`

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center px-4" onClick={onCancel}>
      <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" />
      <div
        className="relative w-full max-w-lg glass-card rounded-2xl p-6 pb-7 shadow-lg"
        style={{ animation: 'slideUp 0.2s ease' }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Başlık */}
        <div className="flex items-center justify-between mb-5">
          <p className="text-base font-semibold text-white">
            {isAutoGenerated ? '🚚 Kurye Görevi' : isCourierOffer ? '📦 Teklif Onayı' : task.task_type === 'second_hand' ? '🛍️ Satın Almayı Onayla' : '✅ Görevi Onayla'}
          </p>
          <button
            onClick={onCancel}
            className="w-8 h-8 rounded-lg border border-white/15 flex items-center justify-center hover:bg-white/5 transition-colors"
          >
            <X size={15} className="text-slate-400" />
          </button>
        </div>

        {/* İlan Detayı */}
        <div className="bg-white/5 border border-white/15 rounded-xl p-4 mb-4 space-y-3">
          <div>
            <p className="text-xs text-slate-400 mb-0.5 font-medium">İlan</p>
            <p className="text-sm font-semibold text-white leading-snug">{task.title}</p>
          </div>
          {task.description && (
            <div>
              <p className="text-xs text-slate-400 mb-0.5 font-medium">Açıklama</p>
              <p className="text-xs text-slate-300 leading-relaxed line-clamp-3">{task.description}</p>
            </div>
          )}
          <div className="flex flex-wrap gap-2 pt-1">
            <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-lg border text-[10px] font-medium ${typeConf.cls}`}>
              <TypeIcon size={9} />
              {typeConf.label}
            </span>
            {locationDisplay && (
              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-lg border text-[10px] font-medium bg-white/5 text-slate-300 border-white/15">
                <MapPin size={9} />
                {locationDisplay}
              </span>
            )}
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-lg border text-[10px] font-bold bg-teal-500/10 text-teal-300 border-teal-500/20">
              {task.effective_reward || task.reward_kredi} KP
            </span>
          </div>
        </div>

        {/* Ödeme Notu */}
        <div className={`flex items-start gap-2.5 p-3 rounded-xl mb-5 ${
          isCourierOffer
            ? 'bg-amber-500/10 border border-amber-500/20'
            : isAutoGenerated
              ? 'bg-teal-500/10 border border-teal-500/20'
              : 'bg-white/5 border border-white/15'
        }`}>
          {isCourierOffer
            ? <AlertCircle size={14} className="text-amber-500 flex-shrink-0 mt-0.5" />
            : <CheckCircle size={14} className={`flex-shrink-0 mt-0.5 ${isAutoGenerated ? 'text-amber-400' : 'text-slate-300'}`} />
          }
          <p className={`text-xs leading-relaxed ${
            isCourierOffer ? 'text-amber-200/80' : isAutoGenerated ? 'text-teal-200/80' : 'text-slate-300'
          }`}>
            {paymentNote}
          </p>
        </div>

        {/* Butonlar */}
        <div className="flex gap-3">
          <button
            onClick={onCancel}
            disabled={loading}
            className="btn-secondary flex-1 py-3 text-sm disabled:opacity-40"
          >
            Vazgeç
          </button>
          <button
            onClick={onConfirm}
            disabled={loading}
            className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-lg text-sm font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed
              ${isCourierOffer
                ? 'bg-amber-500 text-amber-950 hover:bg-amber-600 hover:-translate-y-0.5'
                : 'btn-primary'
              }`}
          >
            {loading
              ? <><Loader size={15} className="animate-spin" /> İşleniyor...</>
              : isCourierOffer
                ? <><Truck size={15} /> Teklifi Kabul Et</>
                : task.task_type === 'second_hand'
                  ? <><Tag size={15} /> Satın Al</>
                  : <><CheckCircle size={15} /> Kabul Et</>
            }
          </button>
        </div>
      </div>
    </div>
  )
}

// ── İletişim + Mesaj Modalı ─────────────────────────────────
function ContactDrawer({ task, onClose }) {
  const [contact, setContact] = useState(null)
  const [loading, setLoading] = useState(true)
  const [msgText, setMsgText] = useState('')
  const [sending, setSending] = useState(false)
  const [msgSent, setMsgSent] = useState(false)
  const [error,   setError]   = useState('')

  useEffect(() => {
    if (!task?.creator_id) { setLoading(false); return }
    api.get(`/contact/${task.creator_id}`)
      .then(res => setContact(res.data.contact))
      .catch(() => setError('İletişim bilgisi yüklenemedi.'))
      .finally(() => setLoading(false))
  }, [task?.creator_id])

  const handleSendMessage = async () => {
    if (!msgText.trim()) return
    setSending(true)
    setError('')
    try {
      await api.post('/messages', {
        receiver_id:     task.creator_id,
        message_text:    msgText.trim(),
        related_task_id: task.id,
      })
      setMsgSent(true)
      setMsgText('')
    } catch (err) {
      setError(err.response?.data?.message || 'Mesaj gönderilemedi.')
    } finally {
      setSending(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center px-4" onClick={onClose}>
      <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" />
      <div
        className="relative w-full max-w-lg glass-card rounded-2xl p-6 pb-8 shadow-lg"
        style={{ animation: 'slideUp 0.25s ease' }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Başlık */}
        <div className="flex items-center justify-between mb-5">
          <div>
            <p className="text-base font-semibold text-white">{task.creator_name} ile İletişim</p>
            <p className="text-xs text-slate-400 mt-0.5 line-clamp-1">{task.title}</p>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-lg border border-white/15 flex items-center justify-center hover:bg-white/5 transition-colors"
          >
            <X size={15} className="text-slate-400" />
          </button>
        </div>

        {/* Mesaj Gönder */}
        <div className="mb-5">
          <label className="text-xs font-semibold text-slate-300 mb-2 block">Mesaj Gönder</label>
          {msgSent ? (
            <div className="p-3 rounded-lg bg-emerald-50 border border-emerald-200 text-center">
              <p className="text-sm text-amber-400 font-medium">✅ Mesajın gönderildi!</p>
            </div>
          ) : (
            <div className="flex gap-2">
              <input
                type="text"
                value={msgText}
                onChange={(e) => { setMsgText(e.target.value); setError('') }}
                onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                placeholder={`${task.creator_name}'e mesaj yaz...`}
                className="input-field flex-1 py-2.5 text-sm"
              />
              <button
                onClick={handleSendMessage}
                disabled={sending || !msgText.trim()}
                className="btn-primary px-4 flex items-center gap-1.5 disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:translate-y-0"
              >
                {sending ? <Loader size={15} className="animate-spin" /> : <Send size={15} />}
              </button>
            </div>
          )}
          {error && <p className="text-xs text-red-500 mt-2">{error}</p>}
        </div>

        {/* Sosyal Medya Linkleri */}
        <div>
          <label className="text-xs font-semibold text-slate-300 mb-2 block">Sosyal Medya</label>
          {loading ? (
            <div className="space-y-2">
              {[1,2].map(i => <div key={i} className="h-14 bg-white/10 animate-pulse rounded-xl" />)}
            </div>
          ) : !contact || (!contact.show_instagram && !contact.show_linkedin && !contact.show_phone) ? (
            <p className="text-sm text-slate-400 text-center py-4">Paylaşılan sosyal medya bilgisi yok.</p>
          ) : (
            <div className="space-y-2">
              {contact.instagram_handle && contact.show_instagram && (
                <a
                  href={`https://instagram.com/${contact.instagram_handle}`}
                  target="_blank" rel="noreferrer"
                  className="flex items-center gap-3 p-3 glass-card rounded-xl hover:bg-white/5 hover:border-slate-300 transition-all"
                >
                  <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-pink-500 to-orange-400 flex items-center justify-center">
                    <span className="text-sm">📸</span>
                  </div>
                  <div>
                    <p className="text-xs text-slate-400">Instagram</p>
                    <p className="text-sm font-medium text-white">@{contact.instagram_handle}</p>
                  </div>
                  <ArrowRight size={16} className="ml-auto text-slate-300" />
                </a>
              )}
              {contact.linkedin_url && contact.show_linkedin && (
                <a
                  href={contact.linkedin_url}
                  target="_blank" rel="noreferrer"
                  className="flex items-center gap-3 p-3 glass-card rounded-xl hover:bg-white/5 hover:border-slate-300 transition-all"
                >
                  <div className="w-9 h-9 rounded-xl bg-blue-600 flex items-center justify-center">
                    <span className="text-sm">💼</span>
                  </div>
                  <div>
                    <p className="text-xs text-slate-400">LinkedIn</p>
                    <p className="text-sm font-medium text-white">Profili Görüntüle</p>
                  </div>
                  <ArrowRight size={16} className="ml-auto text-slate-300" />
                </a>
              )}
              {contact.phone_number && contact.show_phone && (
                <a
                  href={`tel:${contact.phone_number}`}
                  className="flex items-center gap-3 p-3 glass-card rounded-xl hover:bg-white/5 hover:border-slate-300 transition-all"
                >
                  <div className="w-9 h-9 rounded-xl bg-emerald-600 flex items-center justify-center">
                    <span className="text-sm">📞</span>
                  </div>
                  <div>
                    <p className="text-xs text-slate-400">Telefon</p>
                    <p className="text-sm font-medium text-white">{contact.phone_number}</p>
                  </div>
                  <ArrowRight size={16} className="ml-auto text-slate-300" />
                </a>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ── Ana TaskCard ────────────────────────────────────────────
export default function TaskCard({ task, onAssign, isOwnTask = false }) {
  const [showContact, setShowContact] = useState(false)
  const [showConfirm, setShowConfirm] = useState(false)
  const [assigning,   setAssigning]   = useState(false)
  const navigate = useNavigate()

  const typeConf = TASK_TYPE_CONFIG[task.task_type] || TASK_TYPE_CONFIG.skill_exchange
  const TypeIcon = typeConf.icon

  const locationDisplay = task.task_type === 'courier_offer' && task.from_location && task.to_location
    ? { label: `${LOCATION_CONFIG[task.from_location]?.label} → ${LOCATION_CONFIG[task.to_location]?.label}`, cls: 'bg-emerald-50 text-amber-400 border-emerald-200' }
    : task.location ? LOCATION_CONFIG[task.location] : null

  const handleConfirmAssign = async () => {
    setAssigning(true)
    await onAssign?.(task)
    setAssigning(false)
    setShowConfirm(false)
  }

  return (
    <>
      <div className="glass-card rounded-xl p-4 transition-all duration-200 hover:-translate-y-0.5 hover:shadow-md hover:border-slate-300">
        {/* Üst: Oluşturan */}
        <div className="flex items-start justify-between mb-3">
          <div className="flex items-center gap-2">
            <div className="w-9 h-9 rounded-xl bg-amber-500-amber-950 flex-shrink-0">
              {task.creator_name?.[0]}
            </div>
            <div>
              <div className="flex items-center gap-1">
                <button
                  onClick={(e) => { e.stopPropagation(); navigate(`/profile/${task.creator_id}`) }}
                  className="text-sm font-semibold text-white hover:text-slate-300 transition-colors"
                >
                  {task.creator_name}
                </button>
              </div>
              <StarRating value={task.rating_average} count={task.rating_count} />
            </div>
          </div>
          <div className="text-right flex-shrink-0">
            {isOwnTask ? (
              <p className="text-[9px] text-slate-400 mb-0.5 uppercase tracking-wide font-medium">Benim İlanım</p>
            ) : task.task_type === 'courier_offer' || task.task_type === 'second_hand' ? (
              <p className="text-[9px] text-amber-600 mb-0.5 uppercase tracking-wide font-medium">Sen Ödüyorsun</p>
            ) : (
              <p className="text-[9px] text-amber-400 mb-0.5 uppercase tracking-wide font-medium">Yaparak Kazan</p>
            )}
            <p className="text-base font-bold text-amber-400 leading-none">
              {task.effective_reward || task.reward_kredi} KP
            </p>
          </div>
        </div>

        {task.image_url && (
          <div className="mb-3 rounded-xl overflow-hidden border border-white/10 max-h-48 flex items-center justify-center bg-black/20">
            <img 
              src={`http://localhost:3000/uploads/${task.image_url}`} 
              alt={task.title}
              className="w-full h-full object-contain max-h-48"
            />
          </div>
        )}

        <h3 className="text-sm font-semibold text-white mb-1 line-clamp-1">{task.title}</h3>
        <p className="text-xs text-slate-400 line-clamp-2 mb-3 leading-relaxed">{task.description}</p>

        <div className="flex flex-wrap gap-1.5 mb-4">
          <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-lg border text-[10px] font-medium ${typeConf.cls}`}>
            <TypeIcon size={9} />
            {typeConf.label}
          </span>
          {locationDisplay && (
            <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-lg border text-[10px] font-medium ${locationDisplay.cls}`}>
              <MapPin size={9} />
              {locationDisplay.label}
            </span>
          )}
        </div>

        <div className="flex gap-2">
          <button
            onClick={() => !isOwnTask && setShowConfirm(true)}
            disabled={isOwnTask}
            className={`flex-1 flex items-center justify-center gap-1.5 text-sm py-2.5 rounded-lg font-semibold transition-all duration-200
              ${isOwnTask
                ? 'bg-white/10 border border-white/15 text-slate-300 cursor-not-allowed'
                : task.task_type === 'courier_offer'
                  ? 'bg-amber-500 text-amber-950 hover:bg-amber-600 hover:-translate-y-0.5 shadow-sm'
                  : 'btn-primary'
              }`}
          >
            {isOwnTask ? (
              <span>Benim İlanım</span>
            ) : task.task_type === 'courier_offer' ? (
              <><span>Teklifi Kabul Et</span><ArrowRight size={14} /></>
            ) : task.task_type === 'second_hand' ? (
              <><span>Satın Al</span><ArrowRight size={14} /></>
            ) : (
              <><span>Görevi Al</span><ArrowRight size={14} /></>
            )}
          </button>
          <button
            onClick={() => setShowContact(true)}
            className="btn-secondary flex items-center justify-center gap-1.5 px-3 text-sm"
          >
            <MessageCircle size={15} />
            <span>İletişim</span>
          </button>
        </div>
      </div>

      {showConfirm && (
        <ConfirmAssignModal
          task={task}
          loading={assigning}
          onConfirm={handleConfirmAssign}
          onCancel={() => setShowConfirm(false)}
        />
      )}

      {showContact && (
        <ContactDrawer task={task} onClose={() => setShowContact(false)} />
      )}
    </>
  )
}
